database:
  # This is the name of the database where the data is stored
  db: database/myworld.sqlite
  # Should be either replace or append depending on the action needed.
  if_exists: replace
  # Database table
  general_table: myworld
  people_table: people

total_records: 1000